title: Partly Cloudy
author:
  name: Josh Gavant
  email: joshgavant@gmail.com
twitter_username: joshugav
github_username:  joshgav

description: A blog about cloud infrastructure and cloud-native application patterns and practices.
url: "https://blog.joshgav.com/"
permalink: /:collection/:slug

theme: jekyll-theme-hydejack
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-avatar
paginate: 10
paginate_path: '/:num/'
show_excerpts: false
menu:
  - title: About Josh
    url:   /about