title: Partly Cloudy
author: Josh Gavant
email: joshgavant@gmail.com
description: >-
  A blog about cloud infrastructure and cloud-native application patterns and
  practices.
baseurl: ""
url: "https://blog.joshgav.com/"
twitter_username: joshugav
github_username:  joshgav

theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
header_pages:
 - about.md
minima:
  social_links:
    twitter: joshugav
    github: joshgav
    linkedin: joshgav

show_excerpts: false
